### ISSUE TITLE
Rework account settings

### ISSUE THREAD

**Issue by GonozalIX** [JibuCorporate/sema-jibu-core#9]
The settings page has to be reworked to avoid confusion on customer's side.
This is a collection of all related tasks which have to be done for this:

- [ ] #3: Hard-coded SEMA url
- [ ] #5: Restrict user to certain kiosks
- [ ] #8: On first app start show login screen instead of settings
